# Generated by Django 6.0.1 on 2026-01-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=50)),
            ],
        ),
    ]
